root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/users/main.go"
bin = "tmp/main"
full_bin = ""
exclude_dir = ["vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_file = ["*_test.go"]
exclude_regex = []
follow_symlink = true

[log]
time = true

[misc]
clean_on_exit = true