version: '3'

tasks:
  run:local:
    cmd: docker-compose -f docker-compose.local.yml up app
    desc: "Start auto compile watching with local env"

  run:dev:
    cmd: air
    desc: "Start auto compile watching with dev env"

  run:prod:
    env:
      GO_ENV: "production"
    cmd: air
    desc: "Start auto compile watching with prod env"

  run:redis:
    cmd: docker-compose -f docker-compose.local.yml up redis

  run:redis-insight:
    cmd: docker-compose -f docker-compose.local.yml up redis-insight

  run:db:
    cmd: docker-compose -f docker-compose.local.yml up db

  run:adminer:
    cmd: docker-compose -f docker-compose.local.yml up adminer
